name: 'YAML File Validation'
description: 'This action is used to validate a YAML file with a custom schema.'
inputs:
  yaml-file-path:
    description: 'The path of the yaml file to validate.'
    required: true
  schema-file-path:
    description: 'The schema file used to validate yaml file.  If omitted or set to ""SAM"", the IM-OPEN SAM schema format will be used.'
    required: true
    default: 'SAM'
runs:
  using: 'node12'
  main: './dist/index.js'
