name: 'YAML File Validation'
description: 'This action is used to validate a YAML file with a custom schema.'

inputs:
  yaml-file-path:
    description: 'The path of the yaml file to validate.'
    required: true
  schema-file-path:
    description: 'The schema file used to validate yaml file.  If omitted or set to ""SAM"", the IM-OPEN SAM schema format will be used.'
    required: false
    default: 'SAM'
  log-level:
    description: "The severity level of information to include the action's logging. Accepted values are information, warning, and failure. "
    required: false
    default: 'information'
  output-json:
    description: 'Specify whether or not to output a json document with the results. Accepts true or false. It will only produce an output if no failures occur.'
    required: false
    default: 'false'

outputs:
  validation-outcome:
    description: 'The results of the file validation. Will be success, warning, or failed. Defaults to `information`.'
  json-output:
    description: 'A json conversion of the yaml file.'

runs:
  using: 'node16'
  main: './dist/index.js'
