name: 'YAML File Validation'
description: 'Checks structure of yaml files against a pre-defined schema'
inputs:
  yaml-file:
    description: 'the yaml file to validate'
    required: true
  schema-file:
    description: 'the schema file used to validate yaml file'
    required: true
runs:
  using: 'node12'
  main: './dist/index.js'
